steps:
  # Builds Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}']
  
  # running docker-compose
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']

  # Deploy an image from Container Registry to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - '${_GCP_CLOUD_RUN_NAME}'
    - '--image'
    - 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}'
    - '--region'
    - '${_GCP_REGION}'
    - '--platform'
    - 'managed'
    - '--cpu'
    - '${_CPUS}'
    - '--concurrency'
    - '${_CONCURRENCY}'
    - '--memory'
    - '${_MEMORY}'
    - '--max-instances'
    - '${_MAX_INSTANCES}'
    - '--allow-unauthenticated'
  
images:
  - 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}'

substitutions:
  _GCP_PROJECT: 'cortex-287319'
  _GCP_REGION: 'us-east1'
  _GCP_CLOUD_RUN_NAME: 'aeolus-airflow'
  _DOCKER_IMAGE : 'aeolus-airflow-image'
  _MAX_INSTANCES: '3'
  _CONCURRENCY: '100'
  _CPUS: '2'
  _MEMORY: '512'